//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FaceliftEntities : DbContext
    {
        public FaceliftEntities()
            : base("name=FaceliftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InvoiceEmail> InvoiceEmails { get; set; }
        public virtual DbSet<LogAccidentDocument> LogAccidentDocuments { get; set; }
        public virtual DbSet<LogAccidentHeader> LogAccidentHeaders { get; set; }
        public virtual DbSet<LogCycleCountDocument> LogCycleCountDocuments { get; set; }
        public virtual DbSet<LogCycleCountHeader> LogCycleCountHeaders { get; set; }
        public virtual DbSet<LogInspectionDocument> LogInspectionDocuments { get; set; }
        public virtual DbSet<LogInspectionHeader> LogInspectionHeaders { get; set; }
        public virtual DbSet<LogRecallDocument> LogRecallDocuments { get; set; }
        public virtual DbSet<LogRecallHeader> LogRecallHeaders { get; set; }
        public virtual DbSet<LogRegistrationDocument> LogRegistrationDocuments { get; set; }
        public virtual DbSet<LogRegistrationHeader> LogRegistrationHeaders { get; set; }
        public virtual DbSet<LogScanTagIdNotRegister> LogScanTagIdNotRegister { get; set; }
        public virtual DbSet<LogShipmentDocument> LogShipmentDocuments { get; set; }
        public virtual DbSet<LogShipmentHeader> LogShipmentHeaders { get; set; }
        public virtual DbSet<LogShipmentOfflineHeader> LogShipmentOfflineHeaders { get; set; }
        public virtual DbSet<LogShipmentOfflineItem> LogShipmentOfflineItems { get; set; }
        public virtual DbSet<MsBillingConfiguration> MsBillingConfigurations { get; set; }
        public virtual DbSet<MsCompany> MsCompanies { get; set; }
        public virtual DbSet<MsDriver> MsDrivers { get; set; }
        public virtual DbSet<MsEquipment> MsEquipments { get; set; }
        public virtual DbSet<MsMainMenu> MsMainMenus { get; set; }
        public virtual DbSet<MsMenu> MsMenus { get; set; }
        public virtual DbSet<MsPallet> MsPallets { get; set; }
        public virtual DbSet<MsPalletAging> MsPalletAgings { get; set; }
        public virtual DbSet<MsPalletType> MsPalletTypes { get; set; }
        public virtual DbSet<MsProducer> MsProducers { get; set; }
        public virtual DbSet<MsRole> MsRoles { get; set; }
        public virtual DbSet<MsRolePermission> MsRolePermissions { get; set; }
        public virtual DbSet<MsStatusType> MsStatusTypes { get; set; }
        public virtual DbSet<MsTransporter> MsTransporters { get; set; }
        public virtual DbSet<MsTransporterAccess> MsTransporterAccesses { get; set; }
        public virtual DbSet<MsTruck> MsTrucks { get; set; }
        public virtual DbSet<MsUser> MsUsers { get; set; }
        public virtual DbSet<MsWarehouse> MsWarehouses { get; set; }
        public virtual DbSet<MsWarehouseAccess> MsWarehouseAccesses { get; set; }
        public virtual DbSet<MsWarehouseCategory> MsWarehouseCategories { get; set; }
        public virtual DbSet<MsWarehouseCompany> MsWarehouseCompanies { get; set; }
        public virtual DbSet<NLog> NLogs { get; set; }
        public virtual DbSet<PalletAgingDaily> PalletAgingDailies { get; set; }
        public virtual DbSet<PalletAgingDetail> PalletAgingDetails { get; set; }
        public virtual DbSet<TrxAccidentHeader> TrxAccidentHeaders { get; set; }
        public virtual DbSet<TrxAccidentItem> TrxAccidentItems { get; set; }
        public virtual DbSet<TrxBillingRentHistoryHeader> TrxBillingRentHistoryHeaders { get; set; }
        public virtual DbSet<TrxBillingRentHistoryItem> TrxBillingRentHistoryItems { get; set; }
        public virtual DbSet<TrxCycleCountHeader> TrxCycleCountHeaders { get; set; }
        public virtual DbSet<TrxCycleCountItem> TrxCycleCountItems { get; set; }
        public virtual DbSet<TrxInspectionHeader> TrxInspectionHeaders { get; set; }
        public virtual DbSet<TrxInspectionItem> TrxInspectionItems { get; set; }
        public virtual DbSet<TrxInvoiceDeffect> TrxInvoiceDeffects { get; set; }
        public virtual DbSet<TrxInvoiceDeffectItem> TrxInvoiceDeffectItems { get; set; }
        public virtual DbSet<TrxInvoiceRentHeader> TrxInvoiceRentHeaders { get; set; }
        public virtual DbSet<TrxRecallHeader> TrxRecallHeaders { get; set; }
        public virtual DbSet<TrxRecallItem> TrxRecallItems { get; set; }
        public virtual DbSet<TrxRegistrationHeader> TrxRegistrationHeaders { get; set; }
        public virtual DbSet<TrxRegistrationItem> TrxRegistrationItems { get; set; }
        public virtual DbSet<TrxShipmentHeader> TrxShipmentHeaders { get; set; }
        public virtual DbSet<TrxShipmentItem> TrxShipmentItems { get; set; }
        public virtual DbSet<TrxShipmentItemTemp> TrxShipmentItemTemps { get; set; }
        public virtual DbSet<VwAccidentItem> VwAccidentItems { get; set; }
        public virtual DbSet<VwAgingShipment> VwAgingShipments { get; set; }
        public virtual DbSet<VwBillingRentDetail> VwBillingRentDetails { get; set; }
        public virtual DbSet<VwBillingRentHistoryItem> VwBillingRentHistoryItems { get; set; }
        public virtual DbSet<VwCycleCountItem> VwCycleCountItems { get; set; }
        public virtual DbSet<VwInvoiceRent> VwInvoiceRents { get; set; }
        public virtual DbSet<VwPallet> VwPallets { get; set; }
        public virtual DbSet<VwPalletAge> VwPalletAges { get; set; }
        public virtual DbSet<VwPalletAging> VwPalletAgings { get; set; }
        public virtual DbSet<VwPalletBilling> VwPalletBillings { get; set; }
        public virtual DbSet<VwPalletDeffectHistory> VwPalletDeffectHistories { get; set; }
        public virtual DbSet<VwPalletGroup> VwPalletGroups { get; set; }
        public virtual DbSet<VwPalletGroup2> VwPalletGroup2 { get; set; }
        public virtual DbSet<VwPalletHistory> VwPalletHistories { get; set; }
        public virtual DbSet<VwPalletMovement> VwPalletMovements { get; set; }
        public virtual DbSet<VwPalletShipment> VwPalletShipments { get; set; }
        public virtual DbSet<VwPalletWarehouse> VwPalletWarehouses { get; set; }
        public virtual DbSet<VwPalletWarehouseCondition> VwPalletWarehouseConditions { get; set; }
        public virtual DbSet<VwRegistrationItem> VwRegistrationItems { get; set; }
        public virtual DbSet<VwShipmentAccident> VwShipmentAccidents { get; set; }
        public virtual DbSet<VwShipmentItem> VwShipmentItems { get; set; }
        public virtual DbSet<LogScanTagIdNotRegister> LogScanTagIdNotRegisters { get; set; }
    
        public virtual int SP_PalletAging()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PalletAging");
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> SP_Test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("SP_Test");
        }
    }
}
