//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRegistrationDocument
    {
        public string LogId { get; set; }
        public string TransactionId { get; set; }
        public string DeliveryNote { get; set; }
        public string Description { get; set; }
        public string PalletTypeId { get; set; }
        public string PalletName { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string PalletOwner { get; set; }
        public string PalletProducer { get; set; }
        public System.DateTime ProducedDate { get; set; }
        public string TransactionStatus { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public int Version { get; set; }
    
        public virtual TrxRegistrationHeader TrxRegistrationHeader { get; set; }
    }
}
