//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogShipmentOfflineHeader
    {
        public string TransactionCode { get; set; }
        public string ShipmentNumber { get; set; }
        public string Remarks { get; set; }
        public string WarehouseName { get; set; }
        public string DestinationName { get; set; }
        public string TransporterName { get; set; }
        public string DriverName { get; set; }
        public string PlateNumber { get; set; }
        public int PalletQty { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UploadedAt { get; set; }
    }
}
