//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogShipmentDocument
    {
        public string LogId { get; set; }
        public string TransactionId { get; set; }
        public string ShipmentNumber { get; set; }
        public string Remarks { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string DestinationId { get; set; }
        public string DestinationCode { get; set; }
        public string DestinationName { get; set; }
        public string TransporterId { get; set; }
        public string TransporterName { get; set; }
        public string DriverId { get; set; }
        public string DriverName { get; set; }
        public string TruckId { get; set; }
        public string PlateNumber { get; set; }
        public int PalletQty { get; set; }
        public string TransactionStatus { get; set; }
        public string ShipmentStatus { get; set; }
        public bool IsDeleted { get; set; }
        public string AccidentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public int Version { get; set; }
    
        public virtual TrxShipmentHeader TrxShipmentHeader { get; set; }
    }
}
