//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsEquipment
    {
        public string EquipmentId { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Ip { get; set; }
        public string port { get; set; }
        public bool IsActive { get; set; }
        public bool Receive { get; set; }
        public bool Ship { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    }
}
