//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsPalletAging
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsPalletAging()
        {
            this.TrxBillingRentHistoryItems = new HashSet<TrxBillingRentHistoryItem>();
        }
    
        public string AgingId { get; set; }
        public string PalletId { get; set; }
        public string AgingType { get; set; }
        public string WarehouseId { get; set; }
        public System.DateTime ReceivedAt { get; set; }
        public int CurrentMonth { get; set; }
        public int CurrentYear { get; set; }
        public int TotalMinutes { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MsPallet MsPallet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxBillingRentHistoryItem> TrxBillingRentHistoryItems { get; set; }
        public virtual MsWarehouse MsWarehouse { get; set; }
    }
}
