//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsPallet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsPallet()
        {
            this.TrxBillingRentHistoryItems = new HashSet<TrxBillingRentHistoryItem>();
            this.MsPalletAgings = new HashSet<MsPalletAging>();
        }
    
        public string TagId { get; set; }
        public string PalletCode { get; set; }
        public string PalletTypeId { get; set; }
        public string PalletName { get; set; }
        public string PalletCondition { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string CompanyId { get; set; }
        public string PalletOwner { get; set; }
        public string PalletProducer { get; set; }
        public System.DateTime ProducedDate { get; set; }
        public string Description { get; set; }
        public string SapId { get; set; }
        public string RegisteredBy { get; set; }
        public System.DateTime RegisteredAt { get; set; }
        public string ReceivedBy { get; set; }
        public System.DateTime ReceivedAt { get; set; }
        public string PalletMovementStatus { get; set; }
        public string LastTransactionName { get; set; }
        public string LastTransactionCode { get; set; }
        public System.DateTime LastTransactionDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MsCompany MsCompany { get; set; }
        public virtual MsPalletType MsPalletType { get; set; }
        public virtual MsProducer MsProducer { get; set; }
        public virtual MsWarehouse MsWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxBillingRentHistoryItem> TrxBillingRentHistoryItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsPalletAging> MsPalletAgings { get; set; }
    }
}
