//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsRolePermission
    {
        public int PermissionId { get; set; }
        public string RoleId { get; set; }
        public int MenuId { get; set; }
    
        public virtual MsMenu MsMenu { get; set; }
        public virtual MsRole MsRole { get; set; }
    }
}
