//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsUser()
        {
            this.MsWarehouseAccesses = new HashSet<MsWarehouseAccess>();
        }
    
        public string Username { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string FullName { get; set; }
        public string RoleId { get; set; }
        public string LastVisitUrl { get; set; }
        public Nullable<System.DateTime> LastVisitAt { get; set; }
        public Nullable<System.DateTime> LastLoginAt { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> ChPassAt { get; set; }
        public string DefaultWarehouseId { get; set; }
    
        public virtual MsRole MsRole { get; set; }
        public virtual MsWarehouse MsWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsWarehouseAccess> MsWarehouseAccesses { get; set; }
    }
}
