//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsWarehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsWarehouse()
        {
            this.MsPallets = new HashSet<MsPallet>();
            this.MsPalletAgings = new HashSet<MsPalletAging>();
            this.MsTransporterAccesses = new HashSet<MsTransporterAccess>();
            this.MsUsers = new HashSet<MsUser>();
            this.MsWarehouseAccesses = new HashSet<MsWarehouseAccess>();
            this.MsWarehouseCompanies = new HashSet<MsWarehouseCompany>();
            this.TrxBillingRentHistoryHeaders = new HashSet<TrxBillingRentHistoryHeader>();
            this.TrxRegistrationHeaders = new HashSet<TrxRegistrationHeader>();
            this.TrxShipmentHeaders = new HashSet<TrxShipmentHeader>();
            this.TrxShipmentHeaders1 = new HashSet<TrxShipmentHeader>();
        }
    
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseAlias { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string PIC1 { get; set; }
        public string PIC2 { get; set; }
        public int MaxCapacity { get; set; }
        public int CategoryId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsPallet> MsPallets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsPalletAging> MsPalletAgings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsTransporterAccess> MsTransporterAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsUser> MsUsers { get; set; }
        public virtual MsWarehouseCategory MsWarehouseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsWarehouseAccess> MsWarehouseAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsWarehouseCompany> MsWarehouseCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxBillingRentHistoryHeader> TrxBillingRentHistoryHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxRegistrationHeader> TrxRegistrationHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxShipmentHeader> TrxShipmentHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxShipmentHeader> TrxShipmentHeaders1 { get; set; }
    }
}
