//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletAgingDaily
    {
        public string AgingId { get; set; }
        public string WarehouseId { get; set; }
        public string CompanyId { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public int TotalPallet { get; set; }
    }
}
