//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletAgingDetail
    {
        public string AgingId { get; set; }
        public string PalletId { get; set; }
        public string WarehouseId { get; set; }
        public string CompanyId { get; set; }
        public int CurrentMonth { get; set; }
        public int CurrentYear { get; set; }
        public int TotalDays { get; set; }
        public Nullable<System.DateTime> CutOffAt { get; set; }
    }
}
