//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxBillingRentHistoryHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrxBillingRentHistoryHeader()
        {
            this.TrxBillingRentHistoryItems = new HashSet<TrxBillingRentHistoryItem>();
        }
    
        public string TransactionId { get; set; }
        public string TransactionCode { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string AgingType { get; set; }
        public int CurrentMonth { get; set; }
        public int CurrentYear { get; set; }
        public int Tax { get; set; }
        public int Payment { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime StartPeriod { get; set; }
        public System.DateTime LastPeriod { get; set; }
    
        public virtual MsWarehouse MsWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxBillingRentHistoryItem> TrxBillingRentHistoryItems { get; set; }
    }
}
