//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxCycleCountHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrxCycleCountHeader()
        {
            this.LogCycleCountDocuments = new HashSet<LogCycleCountDocument>();
            this.LogCycleCountHeaders = new HashSet<LogCycleCountHeader>();
            this.TrxCycleCountItems = new HashSet<TrxCycleCountItem>();
        }
    
        public string TransactionId { get; set; }
        public string TransactionCode { get; set; }
        public string Remarks { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string TransactionStatus { get; set; }
        public bool IsDeleted { get; set; }
        public string AccidentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogCycleCountDocument> LogCycleCountDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogCycleCountHeader> LogCycleCountHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxCycleCountItem> TrxCycleCountItems { get; set; }
    }
}
