//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxInvoiceDeffect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrxInvoiceDeffect()
        {
            this.TrxInvoiceDeffectItems = new HashSet<TrxInvoiceDeffectItem>();
        }
    
        public string TransactionId { get; set; }
        public string TransactionCode { get; set; }
        public int CurrentMonth { get; set; }
        public int CurrentYear { get; set; }
        public int Allowance { get; set; }
        public int TotalPallet { get; set; }
        public int CurrentDeffect { get; set; }
        public int PreviousDeffect { get; set; }
        public int TotalDeffect { get; set; }
        public int AllowanceQty { get; set; }
        public int TotalExceed { get; set; }
        public int LastExceed { get; set; }
        public int ExceedQty { get; set; }
        public decimal PricePerPallet { get; set; }
        public int Tax { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxInvoiceDeffectItem> TrxInvoiceDeffectItems { get; set; }
    }
}
