//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxInspectionHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrxInspectionHeader()
        {
            this.LogInspectionDocuments = new HashSet<LogInspectionDocument>();
            this.LogInspectionHeaders = new HashSet<LogInspectionHeader>();
            this.TrxInspectionItems = new HashSet<TrxInspectionItem>();
        }
    
        public string TransactionId { get; set; }
        public string TransactionCode { get; set; }
        public string RefNumber { get; set; }
        public string Type { get; set; }
        public string PIC { get; set; }
        public string Classification { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string ApproverWarehouseId { get; set; }
        public string ApproverWarehouseCode { get; set; }
        public string ApproverWarehouseName { get; set; }
        public string Remarks { get; set; }
        public string TransactionStatus { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public string ApprovalStatus { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> IssuedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogInspectionDocument> LogInspectionDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogInspectionHeader> LogInspectionHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxInspectionItem> TrxInspectionItems { get; set; }
    }
}
