//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxRecallItem
    {
        public string TransactionItemId { get; set; }
        public string TransactionId { get; set; }
        public string TagId { get; set; }
        public string PreviousWarehouseId { get; set; }
        public string PreviousWarehouseCode { get; set; }
        public string PreviousWarehouseName { get; set; }
        public string ScannedBy { get; set; }
        public System.DateTime ScannedAt { get; set; }
        public string PreviousPalletCondition { get; set; }
        public string NewPalletCondition { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        public virtual TrxRecallHeader TrxRecallHeader { get; set; }
    }
}
