//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxRegistrationHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrxRegistrationHeader()
        {
            this.LogRegistrationDocuments = new HashSet<LogRegistrationDocument>();
            this.LogRegistrationHeaders = new HashSet<LogRegistrationHeader>();
            this.TrxRegistrationItems = new HashSet<TrxRegistrationItem>();
        }
    
        public string TransactionId { get; set; }
        public string TransactionCode { get; set; }
        public string DeliveryNote { get; set; }
        public string Description { get; set; }
        public string PalletTypeId { get; set; }
        public string PalletName { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string CompanyId { get; set; }
        public string PalletOwner { get; set; }
        public string PalletProducer { get; set; }
        public System.DateTime ProducedDate { get; set; }
        public string TransactionStatus { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogRegistrationDocument> LogRegistrationDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogRegistrationHeader> LogRegistrationHeaders { get; set; }
        public virtual MsCompany MsCompany { get; set; }
        public virtual MsPalletType MsPalletType { get; set; }
        public virtual MsProducer MsProducer { get; set; }
        public virtual MsWarehouse MsWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxRegistrationItem> TrxRegistrationItems { get; set; }
    }
}
