//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxShipmentHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrxShipmentHeader()
        {
            this.LogShipmentDocuments = new HashSet<LogShipmentDocument>();
            this.LogShipmentHeaders = new HashSet<LogShipmentHeader>();
            this.TrxShipmentItems = new HashSet<TrxShipmentItem>();
        }
    
        public string TransactionId { get; set; }
        public string TransactionCode { get; set; }
        public string ShipmentNumber { get; set; }
        public string Remarks { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string DestinationId { get; set; }
        public string DestinationCode { get; set; }
        public string DestinationName { get; set; }
        public string TransporterId { get; set; }
        public string TransporterName { get; set; }
        public string DriverId { get; set; }
        public string DriverName { get; set; }
        public string TruckId { get; set; }
        public string PlateNumber { get; set; }
        public int PalletQty { get; set; }
        public string TransactionStatus { get; set; }
        public string ShipmentStatus { get; set; }
        public bool IsDeleted { get; set; }
        public string AccidentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public int WarningCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogShipmentDocument> LogShipmentDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogShipmentHeader> LogShipmentHeaders { get; set; }
        public virtual MsDriver MsDriver { get; set; }
        public virtual MsTransporter MsTransporter { get; set; }
        public virtual MsTruck MsTruck { get; set; }
        public virtual MsWarehouse MsWarehouse { get; set; }
        public virtual MsWarehouse MsWarehouse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrxShipmentItem> TrxShipmentItems { get; set; }
    }
}
