//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwInvoiceRent
    {
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string CategoryName { get; set; }
        public int CurrentMonth { get; set; }
        public int CurrentYear { get; set; }
        public Nullable<double> TotalBillingRent { get; set; }
        public string MGV { get; set; }
        public Nullable<double> TotalBillingMGV { get; set; }
    }
}
