//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwPalletShipment
    {
        public string TagId { get; set; }
        public string PalletCode { get; set; }
        public string PalletName { get; set; }
        public string PalletCondition { get; set; }
        public string WarehouseName { get; set; }
        public string PalletOwner { get; set; }
        public string PalletProducer { get; set; }
        public System.DateTime ProducedDate { get; set; }
        public string RegisteredBy { get; set; }
        public System.DateTime RegisteredAt { get; set; }
        public string ReceivedBy { get; set; }
        public System.DateTime ReceivedAt { get; set; }
        public string PalletMovementStatus { get; set; }
        public string LastTransactionName { get; set; }
        public string LastTransactionCode { get; set; }
        public System.DateTime LastTransactionDate { get; set; }
        public string OriginId { get; set; }
        public string OriginName { get; set; }
        public string DestinationId { get; set; }
        public string DestinationName { get; set; }
    }
}
