//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwPalletHistory
    {
        public string TagId { get; set; }
        public string PalletCode { get; set; }
        public string PalletTypeId { get; set; }
        public string PalletName { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string OriginId { get; set; }
        public string OriginCode { get; set; }
        public string OriginName { get; set; }
        public string PalletOwner { get; set; }
        public string PalletProducer { get; set; }
        public System.DateTime ProducedDate { get; set; }
        public string TransactionId { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionStatus { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public string ScannedBy { get; set; }
        public Nullable<System.DateTime> ScannedDate { get; set; }
    }
}
