//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwPalletGroup2
    {
        public string PalletTypeId { get; set; }
        public string PalletName { get; set; }
        public string PalletCondition { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public string PalletOwner { get; set; }
        public string PalletProducer { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> TotalPallet { get; set; }
    }
}
