//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwRegistrationItem
    {
        public string TransactionItemId { get; set; }
        public string TransactionId { get; set; }
        public string WarehouseId { get; set; }
        public string TagId { get; set; }
        public string InsertedBy { get; set; }
        public System.DateTime InsertedAt { get; set; }
        public string InsertMethod { get; set; }
        public string ItemStatus { get; set; }
    }
}
