//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facelift_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwShipmentAccident
    {
        public string AccidentTransactionId { get; set; }
        public string AccidentTransactionCode { get; set; }
        public string AccidentRefNumber { get; set; }
        public string AccidentReasonType { get; set; }
        public string AccidentRemarks { get; set; }
        public string AccidentWarehouseId { get; set; }
        public string AccidentWarehouseCode { get; set; }
        public string AccidentWarehouseName { get; set; }
        public string AccidentTransactionStatus { get; set; }
        public bool AccidentIsDeleted { get; set; }
        public string AccidentCreatedBy { get; set; }
        public System.DateTime AccidentCreatedAt { get; set; }
        public string AccidentModifiedBy { get; set; }
        public Nullable<System.DateTime> AccidentModifiedAt { get; set; }
        public string AccidentApprovedBy { get; set; }
        public Nullable<System.DateTime> AccidentApprovedAt { get; set; }
        public string ShipmentTransactionId { get; set; }
        public string ShipmentTransactionCode { get; set; }
        public string ShipmentShipmentNumber { get; set; }
        public string ShipmentRemarks { get; set; }
        public string ShipmentWarehouseId { get; set; }
        public string ShipmentWarehouseCode { get; set; }
        public string ShipmentWarehouseName { get; set; }
        public string ShipmentDestinationId { get; set; }
        public string ShipmentDestinationCode { get; set; }
        public string ShipmentDestinationName { get; set; }
        public string ShipmentTransporterId { get; set; }
        public string ShipmentTransporterName { get; set; }
        public string ShipmentDriverId { get; set; }
        public string ShipmentDriverName { get; set; }
        public string ShipmentTruckId { get; set; }
        public string ShipmentPlateNumber { get; set; }
        public int ShipmentPalletQty { get; set; }
        public string ShipmentTransactionStatus { get; set; }
        public string ShipmentShipmentStatus { get; set; }
        public bool ShipmentIsDeleted { get; set; }
        public string ShipmentAccidentId { get; set; }
        public string ShipmentCreatedBy { get; set; }
        public System.DateTime ShipmentCreatedAt { get; set; }
        public string ShipmentModifiedBy { get; set; }
        public Nullable<System.DateTime> ShipmentModifiedAt { get; set; }
        public string ShipmentApprovedBy { get; set; }
        public Nullable<System.DateTime> ShipmentApprovedAt { get; set; }
    }
}
